#!/usr/bin/env ruby

# capture png file
tmpfile = "/tmp/image_upload#{$$}.png"
imagefile = ARGV[1]

if imagefile && File.exist?(imagefile) then
  system "sips -s format png \"#{imagefile}\" --out \"#{tmpfile}\""
else
  system "screencapture -i \"#{tmpfile}\""
  if File.exist?(tmpfile) then
    system "sips -d profile --deleteColorManagementProperties \"#{tmpfile}\""
  end
end

if !File.exist?(tmpfile) then
  exit
end

# mv to dropbox
dropbox_dir = "~/Dropbox/Public/images"
dropbox_url = "http://dl.dropbox.com/u/964705/images"
filename = "#{Time.now.strftime("%Y%m%d_%H%M%S")}.png"

system "mv #{tmpfile} #{dropbox_dir}/#{filename}"
system "open #{dropbox_url}/#{filename}"
system "echo #{dropbox_url}/#{filename} | pbcopy"

File.delete(tmpfile)

